### ISSUE TITLE
网站挂了，啊喂

### ISSUE THREAD

**Issue by youngerheart** [Bilibili/join-us#2]
第一次见到好神奇！！！
504 Gateway Time-out

The gateway did not receive a timely response from the upstream server or application. Sorry for the inconvenience.
Please report this message and include the following information to us.
Thank you very much!

URL:	https://secure.bilibili.com/secure,cid=178078&aid=107084
Server:	cn-sd-cu
Date:	2015/05/17 20:37:36
Powered by Tengine

**Comment by ctiao** [comment]
fixed
